### ISSUE TITLE
fails at resolving meta-schema references

### ISSUE THREAD

**Issue by Olaf-Wolf3D** [cardinalby/schema-validator-action#4]
Hey! I'm trying to lint schemas that use `https://json-schema.org/draft/2020-12/schema` as their $schema. but your action fails at resolving the references in that schema, though the schema itseld seems to load just fine.
Is there anything you can do about it?

```
Parsing schemas/test.schema.json as JSON...
Parsed to object
"schema" input is not set, reading $schema = "https://json-schema.org/draft/2020-12/schema from schemas/test.schema.json"
Loading schema from URL: https://json-schema.org/draft/2020-12/schema ...
200, undefined bytes loaded, Content-Type: undefined
Parsing https://json-schema.org/draft/2020-12/schema as JSON...
Parsed to object
Error: SchemaError: no such schema <https://json-schema.org/draft/2020-12/meta/core>
```

**Comment by cardinalby** [comment]
Hi! Thanks for creating the issue :)

It seems that the library which is used by the action doesn't support draft 2020-12, I will try to find another one and let you know here. 

You can advice the proper JS lib that is compatible with all versions of JSON schema if you know one.

**Comment by cardinalby** [comment]
@Olaf-Wolf3D Check out `cardinalby/schema-validator-action@v2` version, it has built-in meta-schemas and should validate your schema.

Additionally, in v2 version you can pass own schemas to resolve external `$ref`s in the schema. See the [release notes](https://github.com/cardinalby/schema-validator-action/releases/tag/2.0.0). 

Please let me know if the issue is resolved!

**Comment by Olaf-Wolf3D** [comment]
Thank you! Resolving the references works now!
So that I don't have to update the linter everytime I add or remove schemas, I setup my workflow like this:
```YAML
jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Get JSON schema filenames
        run: |
          schema_files=$(find schemas -name '*.json' -print0 | xargs -0 -I {} sh -c 'printf "%s\0" "{}"' | jq -Rs 'split("\u0000")[:-1]')
          echo "Found JSON schema files: $schema_files"
      - name: Validate all json files using their own $schema properties
        uses: cardinalby/schema-validator-action@v2
        with:
          file: "schemas/*.schema.json"
          refSchemasArray: ${{ steps.get_json_schema_files.outputs.schema_files }}
```

Now I only have to find a way to support ajv's [$data references](https://ajv.js.org/guide/combining-schemas.html#data-reference), since using them fails the validation. I guess I need a fork of the draft 2020 meta-schema that supports them.
